/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006875",
        "surface-container-highest": "#30353d",
        "on-secondary-fixed-variant": "#005233",
        "on-primary-fixed-variant": "#004f58",
        "background": "#0f141b",
        "primary": "#c3f5ff",
        "surface-variant": "#30353d",
        "inverse-surface": "#dee2ec",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002112",
        "on-tertiary-container": "#7a5100",
        "surface-bright": "#343941",
        "tertiary": "#ffead0",
        "primary-fixed-dim": "#00daf3",
        "tertiary-fixed": "#ffddb1",
        "on-surface-variant": "#bac9cc",
        "secondary-fixed-dim": "#00e296",
        "outline-variant": "#3b494c",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2c3138",
        "primary-container": "#00e5ff",
        "on-primary-fixed": "#001f24",
        "surface-container-low": "#171c23",
        "on-primary-container": "#00626e",
        "error": "#ffb4ab",
        "on-tertiary": "#442b00",
        "on-background": "#dee2ec",
        "secondary-fixed": "#4dffb1",
        "on-primary": "#00363d",
        "surface": "#0f141b",
        "surface-container": "#1b2027",
        "secondary": "#bfffd8",
        "surface-dim": "#0f141b",
        "on-surface": "#dee2ec",
        "surface-container-lowest": "#090f15",
        "on-tertiary-fixed": "#291800",
        "surface-container-high": "#252a32",
        "on-secondary-container": "#006943",
        "primary-fixed": "#9cf0ff",
        "tertiary-container": "#ffc775",
        "secondary-container": "#00f2a1",
        "outline": "#849396",
        "on-tertiary-fixed-variant": "#624000",
        "surface-tint": "#00daf3",
        "tertiary-fixed-dim": "#ffba4b",
        "on-secondary": "#003822",
        "mint": "#00e296",
        "amber": "#ffba4b",
        "coral": "#ffb4ab"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "unit": "4px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Bebas Neue", "sans-serif"],
        "headline-lg-mobile": ["Bebas Neue", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["72px", { "lineHeight": "72px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "32px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-lg": ["48px", { "lineHeight": "48px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}

